language: python

matrix:
  fast_finish: true
  include:
  - env: TOX_ENV=py33-django-18
    python: 3.3
  - env: TOX_ENV=py34-django-18
    python: 3.4
  - env: TOX_ENV=py35-django-18
    python: 3.5
  - env: TOX_ENV=py36-django-18
    python: 3.6
  - env: TOX_ENV=py34-django-19
    python: 3.4
  - env: TOX_ENV=py35-django-19
    python: 3.5
  - env: TOX_ENV=py36-django-19
    python: 3.6
  - env: TOX_ENV=py34-django-110
    python: 3.4
  - env: TOX_ENV=py35-django-110
    python: 3.5
  - env: TOX_ENV=py36-django-110
    python: 3.6
  - env: TOX_ENV=py34-django-111
    python: 3.4
  - env: TOX_ENV=py35-django-111
    python: 3.5
  - env: TOX_ENV=py36-django-111
    python: 3.6
  - env: TOX_ENV=py36-django-20
    python: 3.6

install: pip install -r requirements_test.txt

script: tox -e $TOX_ENV

after_success:
- codecov -e TOX_ENV
